#!/usr/bin/env python3
"""Remap raw k-cluster semantic PNGs to 19-class trainIDs using the k-means mapping.

This solves the problem where CUPS trains on 100+ pseudo-classes (making the
classification task unnecessarily hard) when all clusters should be collapsed
to 19 Cityscapes trainIDs.

Input:  pseudo_semantic_raw_k{K}/{split}/{city}/{stem}.png  (values 0 to K-1)
Output: pseudo_semantic_mapped_k{K}/{split}/{city}/{stem}.png  (values 0-18, 255=ignore)

The cluster_to_class mapping comes from kmeans_centroids.npz (generated by
generate_overclustered_semantics.py).

Usage:
    python pseudo_labels/remap_raw_clusters_to_trainid.py \
        --cityscapes_root /path/to/cityscapes \
        --semantic_subdir pseudo_semantic_raw_k100 \
        --centroids_path /path/to/pseudo_semantic_raw_k100/kmeans_centroids.npz \
        --split train

Then regenerate CUPS format with 19 classes:
    python pseudo_labels/convert_to_cups_format.py \
        --cityscapes_root /path/to/cityscapes \
        --semantic_subdir pseudo_semantic_mapped_k100 \
        --output_subdir cups_pseudo_labels_k100_19cls \
        --split train \
        --num_classes 19 --depth_instances \
        --centroids_path /path/to/pseudo_semantic_raw_k100/kmeans_centroids.npz \
        --depth_subdir depth_spidepth \
        --grad_threshold 0.20 --min_instance_area 1000
"""

import argparse
import os
import time

import numpy as np
from PIL import Image
from tqdm import tqdm


IGNORE_LABEL = 255


def main():
    parser = argparse.ArgumentParser(
        description="Remap raw k-cluster semantics to 19-class trainIDs"
    )
    parser.add_argument("--cityscapes_root", type=str, required=True)
    parser.add_argument("--semantic_subdir", type=str, required=True,
                        help="Input subdir with raw cluster PNGs (e.g., pseudo_semantic_raw_k100)")
    parser.add_argument("--centroids_path", type=str, required=True,
                        help="Path to kmeans_centroids.npz with cluster_to_class array")
    parser.add_argument("--output_subdir", type=str, default=None,
                        help="Output subdir (default: pseudo_semantic_mapped_k{K})")
    parser.add_argument("--split", type=str, default="train")
    args = parser.parse_args()

    # Load cluster-to-class mapping
    data = np.load(args.centroids_path)
    cluster_to_class = data["cluster_to_class"]  # (K,) array, values 0-18
    k = len(cluster_to_class)
    print(f"Loaded cluster_to_class mapping: K={k} clusters → 19 trainIDs")

    # Build LUT: raw cluster ID → trainID
    lut = np.full(256, IGNORE_LABEL, dtype=np.uint8)
    for cluster_id in range(k):
        lut[cluster_id] = int(cluster_to_class[cluster_id])

    # Print mapping summary
    CS_NAMES = [
        "road", "sidewalk", "building", "wall", "fence",
        "pole", "traffic light", "traffic sign", "vegetation", "terrain",
        "sky", "person", "rider", "car", "truck",
        "bus", "train", "motorcycle", "bicycle",
    ]
    for cls_id in range(19):
        n = int((cluster_to_class == cls_id).sum())
        print(f"  {CS_NAMES[cls_id]:15s}: {n} clusters → trainID {cls_id}")

    # Setup paths
    if args.output_subdir is None:
        args.output_subdir = f"pseudo_semantic_mapped_k{k}"

    input_dir = os.path.join(args.cityscapes_root, args.semantic_subdir, args.split)
    output_dir = os.path.join(args.cityscapes_root, args.output_subdir, args.split)

    if not os.path.isdir(input_dir):
        print(f"ERROR: Input dir not found: {input_dir}")
        return

    # Find all PNGs
    files = []
    for city in sorted(os.listdir(input_dir)):
        city_dir = os.path.join(input_dir, city)
        if not os.path.isdir(city_dir):
            continue
        for fname in sorted(os.listdir(city_dir)):
            if fname.endswith(".png"):
                files.append((city, fname))

    print(f"\nRemapping {len(files)} images from {args.semantic_subdir}/{args.split}/ → {args.output_subdir}/{args.split}/")

    t0 = time.time()
    for city, fname in tqdm(files, desc="Remapping"):
        # Read raw cluster PNG
        src = os.path.join(input_dir, city, fname)
        raw = np.array(Image.open(src))

        # Apply LUT
        mapped = lut[raw]

        # Save
        dst_dir = os.path.join(output_dir, city)
        os.makedirs(dst_dir, exist_ok=True)
        Image.fromarray(mapped).save(os.path.join(dst_dir, fname))

    elapsed = time.time() - t0
    print(f"Done in {elapsed:.1f}s — output: {output_dir}/")
    print(f"\nNext step: regenerate CUPS format with 19 classes + depth-guided instances:")
    print(f"  python pseudo_labels/convert_to_cups_format.py \\")
    print(f"    --cityscapes_root {args.cityscapes_root} \\")
    print(f"    --semantic_subdir {args.output_subdir} \\")
    print(f"    --output_subdir cups_pseudo_labels_k{k}_19cls \\")
    print(f"    --split {args.split} \\")
    print(f"    --num_classes 19 --depth_instances --use_trainid_things \\")
    print(f"    --depth_subdir depth_spidepth \\")
    print(f"    --grad_threshold 0.20 --min_instance_area 1000")


if __name__ == "__main__":
    main()
